export const hardcodedExpenses = [
    {
        id: '111111111',
        foodExpense: '1',
        utilityExpense: '1',
        otherExpense: '1',
        dateExpensePersonal: '16/10/2024',
    },
    {
        id: '2',
        foodExpense: '2',
        utilityExpense: '2',
        otherExpense: '2',
        dateExpensePersonal: '15/10/2024',
    },
    // {
    //     id: '2',
    //     foodExpense: '2',
    //     utilityExpense: '2',
    //     otherExpense: '2',
    //     dateExpensePersonal: '15/10/2024',
    // }, {
    //     id: '2',
    //     foodExpense: '2',
    //     utilityExpense: '2',
    //     otherExpense: '2',
    //     dateExpensePersonal: '15/10/2024',
    // }, {
    //     id: '2',
    //     foodExpense: '2',
    //     utilityExpense: '2',
    //     otherExpense: '2',
    //     dateExpensePersonal: '15/10/2024',
    // }, {
    //     id: '2',
    //     foodExpense: '2',
    //     utilityExpense: '2',
    //     otherExpense: '2',
    //     dateExpensePersonal: '15/10/2024',
    // }, {
    //     id: '2',
    //     foodExpense: '2',
    //     utilityExpense: '2',
    //     otherExpense: '2',
    //     dateExpensePersonal: '15/10/2024',
    // }, {
    //     id: '2',
    //     foodExpense: '2',
    //     utilityExpense: '2',
    //     otherExpense: '2',
    //     dateExpensePersonal: '15/10/2024',
    // }, {
    //     id: '2',
    //     foodExpense: '2',
    //     utilityExpense: '2',
    //     otherExpense: '2',
    //     dateExpensePersonal: '15/10/2024',
    // }, {
    //     id: '2',
    //     foodExpense: '2',
    //     utilityExpense: '2',
    //     otherExpense: '2',
    //     dateExpensePersonal: '15/10/2024',
    // }, {
    //     id: '2',
    //     foodExpense: '2',
    //     utilityExpense: '2',
    //     otherExpense: '2',
    //     dateExpensePersonal: '15/10/2024',
    // }, {
    //     id: '2',
    //     foodExpense: '2',
    //     utilityExpense: '2',
    //     otherExpense: '2',
    //     dateExpensePersonal: '15/10/2024',
    // }, {
    //     id: '2',
    //     foodExpense: '2',
    //     utilityExpense: '2',
    //     otherExpense: '2',
    //     dateExpensePersonal: '15/10/2024',
    // }, {
    //     id: '2',
    //     foodExpense: '2',
    //     utilityExpense: '2',
    //     otherExpense: '2',
    //     dateExpensePersonal: '15/10/2024',
    // }, {
    //     id: '2',
    //     foodExpense: '2',
    //     utilityExpense: '2',
    //     otherExpense: '2',
    //     dateExpensePersonal: '15/10/2024',
    // }, {
    //     id: '2',
    //     foodExpense: '2',
    //     utilityExpense: '2',
    //     otherExpense: '2',
    //     dateExpensePersonal: '15/10/2024',
    // }, {
    //     id: '2',
    //     foodExpense: '2',
    //     utilityExpense: '2',
    //     otherExpense: '2',
    //     dateExpensePersonal: '15/10/2024',
    // },
]