CREATE TABLE IF NOT EXISTS INCOME_SHOP
(
    ID SERIAL PRIMARY KEY,
    DATE_INCOME     DATE,
    INCOME_CASH     NUMERIC(38, 2),
    INCOME_CASHLESS NUMERIC(38, 2),
    INCOME_OTHER    NUMERIC(38, 2)
);


