CREATE TABLE IF NOT EXISTS PERSONAL_EXPENSES
(
    ID SERIAL PRIMARY KEY,
    DATE_EXPENSE_PERSONAL DATE,
    FOOD_EXPENSE NUMERIC(38, 2),
    OTHER_EXPENSE NUMERIC(38, 2),
    UTILITY_EXPENSE NUMERIC(38, 2)
);


